### ISSUE TITLE
Doesnt seem to connect to my WiFi network

### ISSUE THREAD

**Issue by ivankennethwang** [bamarni/pi64#15]
I've tried all of the settings with WPA2 but I can't seem to connect to my home wifi, nor to my phone hotspot.

Is there anything that I should do first?

**Comment by bamarni** [comment]
How did you try to connect exactly? Have you tried with the `sudo pi64-config` helper tool?

**Comment by ivankennethwang** [comment]
Yes, I tried both using the pi64-config and the one from the lower right system tray icon then manually setting the password of the wifi, then connect. When I went into the pi64-config and type i don't see a feedback though.

**Comment by bamarni** [comment]
Could you paste here the output of the following commands?

    sudo ifconfig
    sudo route -n
    sudo systemctl status dhcpcd

**Comment by bamarni** [comment]
@ivankennethwang : any news about this? Do you still have this issue?

**Comment by ivankennethwang** [comment]
Sorry I havent had the chance to redo it again. I will check if reopen this issue if needed.
