### ISSUE TITLE
Does the current version support google bbr?

### ISSUE THREAD

**Issue by cjl3230** [bamarni/pi64#17]
Does the current version support google bbr?
Google-bbr is useful, so I need the kernel 64bit with bbr run on the Pi3

**Comment by bamarni** [comment]
I'm not familiar with google bbr at all, but I could find this thread on the raspberry pi kernel repo (https://github.com/raspberrypi/linux/issues/1784).

It seems like there needs to be a few kernel configs to enable it, feel free to submit a PR to allow this and I'll gladly merge.

**Comment by cjl3230** [comment]
![kernel](https://user-images.githubusercontent.com/2327445/28649975-34d8028a-72ab-11e7-8a2f-365f3ef566bd.png)

It default build as tcp_bbr.ko.  maybe change .config 
CONFIG_TCP_CONG_BBR=m

**Comment by bamarni** [comment]
fixed by #18
