### ISSUE TITLE
Update from 2017-05-23

### ISSUE THREAD

**Issue by sheychen290** [bamarni/pi64#21]
I have a "2017-05-23 lite" with my self hosted mail server.
It's work great, so it  is possible to install and run pi64-update on this release ?

**Comment by bamarni** [comment]
`pi64-update` essentially just downloads the latest release from https://github.com/bamarni/pi64-kernel/releases and extracts it to the root filesystem. You could do it yourself manually for the first time, it'll give you an updated kernel and also the pi64-update binary.

There is also a file you'd need to create at `/boot/pi64.json` so pi64-update can work for later updates :
```
{"version":"2017-05-23","kernel-version":"2017-07-31"}
```

**Comment by sheychen290** [comment]
Perfect thank
