### ISSUE TITLE
Support HDMI audio and video output?

### ISSUE THREAD

**Issue by cjl3230** [bamarni/pi64#23]
Is pi64 support HDMI audio and video output?

**Comment by bamarni** [comment]
it should, is there a problem with it?

**Comment by olle2** [comment]
Hi all, 
my pi3 outputs both video and audio to HDMI perfectly.

BTW thanks for your pi64 distro, the best of the 64s for PI3 I tested so far! I use it with LXQT, nice.

**Comment by cjl3230** [comment]
Thanks. @bamarni @olle2

**Comment by cjl3230** [comment]
@bamarni my pi3 outputs to HDMI   it show black screen. what can I do?
