### ISSUE TITLE
TIPC Support

### ISSUE THREAD

**Issue by daxj** [bamarni/pi64#25]
Would you be willing to add TIPC modules to your kernel-config.txt for the next release?
E.g.:
```
CONFIG_TIPC=m
CONFIG_TIPC_MEDIA_UDP=y
```

**Comment by bamarni** [comment]
can you try to run `sudo pi64-update`? I've added these config to the latest kernel release.

**Comment by daxj** [comment]
Excellent!  Both the kernel upgrade and new modules worked perfectly: I have tested on a couple of Pis with natively built tipc utils (v2.0.2) and can confirm all is good.

Many thanks, once again, for this superb 64 bit OS.

**Comment by bamarni** [comment]
Cool, let's close this then ^^
