### ISSUE TITLE
CPU temp

### ISSUE THREAD

**Issue by xilopaint** [bamarni/pi64#42]
How can I check the CPU temp in pi64? `vcgencmd` is not present.

**Comment by bamarni** [comment]
What version are you using? vcgencmd should be present.

**Comment by xilopaint** [comment]
Oh! It works with `sudo vcgencmd measure_temp`. I was missing that because in Raspbian we use `/opt/vc/bin/vcgencmd measure_temp`. Why is `sudo` necessary in pi64?

**Comment by xilopaint** [comment]
Sorry, I found it! I was missing it because in Raspbian it's present in `/opt/vc/bin/vcgencmd measure_temp`.

**Comment by DanielSSilva** [comment]
Care to tell me the location @xilopaint pls?

**Comment by xilopaint** [comment]
@DanielSSilva 

/usr/bin/vcgencmd

**Comment by DanielSSilva** [comment]
using which, found it's on `/usr/bin/vcgencmd `
but when i run the command i get this

> pi@raspberrypi:~$ /usr/bin/vcgencmd measure_temp
> VCHI initialization failed

**Comment by xilopaint** [comment]
Try using `sudo`.

**Comment by DanielSSilva** [comment]
nice! that solved. Tks @xilopaint . Using it to mine and yet the temp is lower than with raspbian. Great jobe @bamarni !
