### ISSUE TITLE
Docker installation Error :Either your platform is not easily detectable or is not supported by this installer script.

### ISSUE THREAD

**Issue by bao3** [bamarni/pi64#45]
I user official Docker script

```
curl -fsSL get.docker.com -o get-docker.sh
sh get-docker.sh

```

Get Error:

>
> Executing docker install script, commit: 49ee7c1
>Either your platform is not easily detectable or is not supported by this
>installer script.
>Please visit the following URL for more detailed installation instructions:
>https://docs.docker.com/engine/installation/

>

but I couldn't install Docker. How should I bo ?

**Comment by bamarni** [comment]
I'd suggest you to enable multiarch as explained in the README of this repo : 
```
sudo dpkg --add-architecture armhf
sudo apt-get update
```
Then to follow instructions in https://docs.docker.com/engine/installation/linux/docker-ce/debian/, except that at some point you'd have to run `sudo apt-get install docker-ce:armhf`.
