### ISSUE TITLE
Is there an equivalent to rc.local?

### ISSUE THREAD

**Issue by DanielSSilva** [bamarni/pi64#53]
I'm fairly newbie into linux. I want to run a script upon starting up the pi. On raspbian i know we can use rc.local to achieve that , but I can't find that on this OS. What's the best way to achieve this? 
Thank you!

**Comment by mohakshah** [comment]
You could use `@reboot` in your crontab. See [https://www.raspberrypi.org/documentation/linux/usage/cron.md](https://www.raspberrypi.org/documentation/linux/usage/cron.md)

**Comment by DanielSSilva** [comment]
Totally forgot about crontab.... Why there's no such file as rc.local?

**Comment by bamarni** [comment]
Seems like this has been removed by default on recent Debian (https://stackoverflow.com/questions/44797694/where-is-rc-local-in-debian-9-debian-stretch), you could also use systemd directly for this (https://askubuntu.com/questions/919054/how-do-i-run-a-single-command-at-startup-using-systemd).

**Comment by DanielSSilva** [comment]
@bamarni  thank you for your answer. I've been using rc.local but I forgot that I was on previous version
