### ISSUE TITLE
Get cpu Raspberry temp.

### ISSUE THREAD

**Issue by niccarp** [bamarni/pi64#54]
Hi bamarni.

Did you know if exists some command to get the cpu temp please?

Like this in raspbian original?      /opt/vc/bin/vcgencmd measure_temp

I try it with , apt-get install lm-sensors  but off course doesnt exists sensors :(

This is important to me because my pi is mining MaGi Coin and overclocked so will be great keep under control temp without adding a new sensor or something like that if possible.

Thank you very match,!

**Comment by bamarni** [comment]
Hi, it's in the PATH, so `sudo vcgencmd measure_temp`

**Comment by niccarp** [comment]
Oh, what a noob.  My mistake :) 

Thanks! I will close it
