### ISSUE TITLE
first boot issue

### ISSUE THREAD

**Issue by ric96** [bamarni/pi64#7]
on the latest desktop build
http://imgur.com/BeSHYFD

**Comment by bamarni** [comment]
Thanks for reporting, seems like that file got corrupted somehow during the build process...

I've removed the desktop version from the releases and I'll reupload once it's fixed.

**Comment by bamarni** [comment]
Sorry for not taking the time to re-upload a desktop build for 2017-05-12, however I've just released a new one.

About this error I'm really not sure how it happened, I'll add more checks during image build in the future to avoid that (#8).
