### ISSUE TITLE
problem of load img of pi64 on vmware in windows

### ISSUE THREAD

**Issue by ardashir66** [bamarni/pi64#94]
Hi.
I tried to install your image on vmware but it is not installed and not worked. 
i converted your image to iso by powerISO, but same problem remain. 
thanks in advance

**Comment by CatPurrfect** [comment]
Raspbian and pi64 are ARM images, so you can’t emulate them using ordinary x86_x64 software emulation. You need to emulate the ARM hardware as well. You can achieve that using tools such as ARMware or QEMU.

**Comment by ardashir66** [comment]
thank you so much
